GET http://localhost:5000/api/chats/conversations/with/6a26bff1eab4e05fb9ec9d5d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjFiYzNkYWU5ZGVmNGFkNTUzMGQyMCIsImlhdCI6MTc4MDkyMzgxNiwiZXhwIjoxNzgxNTI4NjE2LCJhdWQiOiJteS1mcm9udGVuZCIsImlzcyI6Im15LWJhY2tlbmQifQ.mmGlEHazQi8Q1qTP2ZbLqPoZFMeujfDoKyQ_rgLF60M
Content-Type: application/json